package bootdemo.hello.model.base;

import java.io.Serializable;

public class LearnResource implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn_resource.id
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn_resource.author
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn_resource.title
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn_resource.url
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table learn_resource
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn_resource.id
     *
     * @return the value of learn_resource.id
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn_resource.id
     *
     * @param id the value for learn_resource.id
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn_resource.author
     *
     * @return the value of learn_resource.author
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn_resource.author
     *
     * @param author the value for learn_resource.author
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn_resource.title
     *
     * @return the value of learn_resource.title
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn_resource.title
     *
     * @param title the value for learn_resource.title
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn_resource.url
     *
     * @return the value of learn_resource.url
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn_resource.url
     *
     * @param url the value for learn_resource.url
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    public void setUrl(String url) {
        this.url = url;
    }
}