/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '17/06/16 10:39' with Gradle 2.14.1
 *
 * @author Administrator, @date 17/06/16 10:39
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
