package bootdemo.hello.dao.base;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import bootdemo.hello.model.base.LearnResource;
import bootdemo.hello.model.base.LearnResourceExample;

public interface LearnResourceDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_resource
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    long countByExample(LearnResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_resource
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    int deleteByExample(LearnResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_resource
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_resource
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    int insert(LearnResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_resource
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    int insertSelective(LearnResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_resource
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    List<LearnResource> selectByExample(LearnResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_resource
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    LearnResource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_resource
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    int updateByExampleSelective(@Param("record") LearnResource record, @Param("example") LearnResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_resource
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    int updateByExample(@Param("record") LearnResource record, @Param("example") LearnResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_resource
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    int updateByPrimaryKeySelective(LearnResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_resource
     *
     * @mbg.generated Mon Jun 19 14:55:40 JST 2017
     */
    int updateByPrimaryKey(LearnResource record);
}