mail:
  fromMail:
    addr: xxoo@xxoo.com
spring:
  datasource:
    url: jdbc:mysql://192.168.81.45:3308/spring?useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: rootPass
  mvc:
    favicon:
      enabled: false
  rabbitmq:
    host: 192.168.81.18
    port: 5672
    username: test
    password: test

  mail:
    host: 192.168.81.18
    port: 25
    username: xxoo@xxoo.com
    password: xxoo
    default-encoding: UTF-8